# 36. Promise.prototype.finally()

### Problem

https://bigfrontend.dev/quiz/Promise-prototype-finally

#

### Problem Description

What does the code snippet below output by `console.log`?

```js
Promise.resolve(1)
  .finally((data) => {
    console.log(data);
    return Promise.reject('error');
  })
  .catch((error) => {
    console.log(error);
    throw 'error2';
  })
  .finally((data) => {
    console.log(data);
    return Promise.resolve(2).then(console.log);
  })
  .then(console.log)
  .catch(console.log);
```

#

### Answer

```
undefined
"error"
undefined
2
"error2"
```

### Explanation

```js
Promise.resolve(1)
  // `Promise.prototype.finally(callback)` returns a `Promise`.
  .finally((data) => {
    console.log(data); // `undefined`, because a `finally` callback will not receive any argument.
    return Promise.reject('error');
  })
  .catch((error) => {
    console.log(error); // `error` from the rejected promise returned by the previous `finally()`
    throw 'error2';
  })
  .finally((data) => {
    console.log(data); // `undefined`, because a `finally` callback will not receive any argument.
    return Promise.resolve(2).then(console.log); // 2
  })
  .then(console.log) // ignored
  .catch(console.log); // `error2` from the previous `catch()`
```
